import type { Idea } from '~/types'

const ideas: Idea[] = [
  {
    id: 1,
    title: 'TAKE PHOTOS OF THE ATTENDANCE REGISTER MONTHLY.',
    description: 'TAKE PHOTOS OF THE ATTENDANCE REGISTER MONTHLY.',
    status: 'approved',
    department: 'Spirits',
    type: 'Time saving',
    strategy: 'Ensure responsiveness and urgency',
    workstation: 'Brandy',
    benefits: 'Ensures quick access to attendance records and reduces administrative time',
    resourcesRequired: 'low',
    submitter: 'Zain Davids',
    evaluator: 'Petrus Eloff',
    impactScore: 3,
    createdAt: '2025-03-18T00:00:00Z'
  },
  {
    id: 2,
    title: 'MODIFY BRANDY BOTTLING CATWALK',
    description: 'MODIFY BRANDY BOTTLING CATWALK',
    status: 'rejected',
    department: 'Spirits',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: 'Worcester',
    benefits: 'Enhances workflow efficiency in bottling process',
    resourcesRequired: 'high',
    submitter: 'Zain Davids',
    evaluator: 'Petrus Eloff',
    impactScore: 3,
    createdAt: '2025-03-18T00:00:00Z'
  },
  {
    id: 3,
    title: 'Install a fixed line on the catwalk between T006 and T007',
    description: 'Install a fixed line on the catwalk between T006 and T007. This will allow the forklift to still be able to service client collections while transferring product to the bottling tanks.',
    status: 'rejected',
    department: 'Quality',
    type: 'Time saving',
    strategy: 'Employ best practice',
    workstation: 'Quality compliance auditing',
    benefits: 'Improves safety and efficiency in product transfer',
    resourcesRequired: 'high',
    submitter: 'Xavier Petersen',
    evaluator: 'Petrus Eloff',
    impactScore: 3,
    createdAt: '2025-03-18T00:00:00Z'
  },
  {
    id: 4,
    title: 'After our monthly EHS Meeting, I highlight the areas on the minutes',
    description: 'After our monthly EHS Meeting, I highlight the areas on the minutes, that requires feedback & send it to the relevant parties for follow up.',
    status: 'approved',
    department: 'Spirits',
    type: 'Improvement',
    strategy: 'Ensure responsiveness and urgency',
    workstation: 'Worcester',
    benefits: 'Streamlines follow-up on EHS action items',
    resourcesRequired: 'low',
    submitter: 'Suzanne Long',
    evaluator: 'Ilse du Toit',
    impactScore: 3,
    createdAt: '2025-03-18T00:00:00Z'
  },
  {
    id: 5,
    title: 'I create only 1x PO for the month for Invertex Loads (Super Syrups)',
    description: 'I create only 1x PO for the month for Invertex Loads (Super Syrups).\nWhere I used to ask weekly if we need; I only create 1x PO for the month (with different lines for the particular delivery dates).\nI send a PO mail to supplier with dates we require delivery; It saves time, and also helps supplier to plan their logistics accordingly.\n',
    status: 'approved',
    department: 'Spirits',
    type: 'Time saving',
    strategy: 'Employ best practice',
    workstation: 'Worcester',
    benefits: 'Reduces procurement administrative time and improves supplier planning',
    resourcesRequired: 'low',
    submitter: 'Suzanne Long',
    evaluator: 'Petrus Eloff',
    impactScore: 3,
    createdAt: '2025-03-18T00:00:00Z'
  },
  {
    id: 6,
    title: 'Blends are printed from SAP on a weekly basis according to the 6 week schedule',
    description: 'Blends are printed from SAP on a weekly basis according to the 6 week schedule and handed to the blender for completion. The 6 week schedule already has the production order number available. When printing the blend we now write the production order number on the blend slip before handing it to the blender.',
    status: 'approved',
    department: 'Spirits',
    type: 'Time saving',
    strategy: 'Ensure responsiveness and urgency',
    workstation: 'Worcester',
    benefits: 'Accelerates blending process with pre-filled order numbers',
    resourcesRequired: 'low',
    submitter: 'Petrus Eloff',
    evaluator: 'Ilse Du Toit',
    impactScore: 3,
    createdAt: '2025-03-18T00:00:00Z'
  },
  {
    id: 7,
    title: 'modification to water tanks spray ball system to CIP sight glasses as well',
    description: 'modification to water tanks spray ball system to CIP sight glasses as well',
    status: 'approved',
    department: 'Spirits',
    type: 'Improvement',
    strategy: 'Employ best practice',
    workstation: 'Worcester',
    benefits: 'Enhances cleaning efficiency for sight glasses',
    resourcesRequired: 'low',
    submitter: 'Peter Adams',
    evaluator: 'Ilse du toit',
    impactScore: 3,
    createdAt: '2025-03-18T00:00:00Z'
  },
  {
    id: 8,
    title: 'LOW Alcohol MCC: We can make base wine and then spin it down to just about zero',
    description: 'LOW Alcohol MCC: We can make base wine and then spin it down to just about zero. Bottle it and add yeast + sugar and have the bottle fermentation to provide bubbles. Probably left with a product RANGE (We can do different sugars, Rose all with dosage) at around 3-5% Alcohol. Premium No/Low. Comes with big taxation wins too.',
    status: 'under_review',
    department: 'Spirits',
    type: 'Product',
    strategy: 'Deliver on customer expectation',
    workstation: 'Worcester',
    benefits: 'Creates premium low-alcohol product line with tax advantages',
    resourcesRequired: 'medium',
    submitter: 'Marco Ventrella',
    evaluator: 'Marco Ventrella',
    impactScore: 3,
    createdAt: '2025-03-18T00:00:00Z'
  },
  {
    id: 9,
    title: 'Broaden the appeal on the bottle product by introducing an Extra Dry variant',
    description: 'Broaden the appeal on the bottle product by introducing an Extra Dry variant on the alcoholic and no alcohol versions.',
    status: 'under_review',
    department: 'Spirits',
    type: 'Product',
    strategy: 'Deliver on customer expectation',
    workstation: 'Worcester',
    benefits: 'Expands product appeal with new variant options',
    resourcesRequired: 'medium',
    submitter: 'Marco Ventrella',
    evaluator: 'Marco Ventrella',
    impactScore: 3,
    createdAt: '2025-03-18T00:00:00Z'
  },
  {
    id: 10,
    title: 'Extent RO water line ontop of bottling tanks, for additions',
    description: 'Extent RO water line ontop of bottling tanks, for additions.',
    status: 'rejected',
    department: 'Spirits',
    type: 'Time saving',
    strategy: 'Continuously improve',
    workstation: 'Worcester',
    benefits: 'Simplifies water additions during bottling',
    resourcesRequired: 'high',
    submitter: 'Marco Swartz',
    evaluator: 'Ilse du Toit',
    impactScore: 3,
    createdAt: '2025-03-18T00:00:00Z'
  },
  {
    id: 11,
    title: 'print COA s when collecting dry goods for blending- reduce traceability time',
    description: 'print COA s when collecting dry goods for blending- reduce traceability time',
    status: 'approved',
    department: 'Spirits',
    type: 'Time saving',
    strategy: 'Ensure responsiveness and urgency',
    workstation: 'Worcester',
    benefits: 'Reduces traceability time for dry goods blending',
    resourcesRequired: 'low',
    submitter: 'Lucinda Bantom',
    evaluator: 'Ilse du Toit',
    impactScore: 3,
    createdAt: '2025-03-18T00:00:00Z'
  },
  {
    id: 12,
    title: 'Catch put for boiler room drainage',
    description: 'Catch put for boiler room drainage',
    status: 'approved',
    department: 'Spirits',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: 'Worcester',
    benefits: 'Improves boiler room drainage system',
    resourcesRequired: 'low',
    submitter: 'Lindelo Zugula',
    evaluator: 'Francois Joubert',
    impactScore: 3,
    createdAt: '2025-03-18T00:00:00Z'
  },
  {
    id: 13,
    title: 'Change the oil line from the SS 1st Rectifying column to put the product into the oils tank',
    description: 'Change the oil line from the SS 1st Rectifying column to put the product into the oils tank and not directly into the Feints column.',
    status: 'approved',
    department: 'Spirits',
    type: 'Time saving',
    strategy: 'Minimize cost',
    workstation: 'Worcester',
    benefits: 'Optimizes oil line routing for better efficiency',
    resourcesRequired: 'low',
    submitter: 'Lourens Stander',
    evaluator: 'Lourens Stander',
    impactScore: 3,
    createdAt: '2025-01-20T00:00:00Z'
  },
  {
    id: 14,
    title: 'Amend the KWV Form Acknowledgment of Audit Non-conformances',
    description: 'Amend the KWV Form Acknowledgment of Audit Non-conformances (Doc No 2020665) to include columns for proposed actions, verification and status.',
    status: 'approved',
    department: 'Spirits',
    type: 'Time saving',
    strategy: 'Ensure responsiveness and urgency',
    workstation: 'WAC',
    benefits: 'Improves audit non-conformance tracking and resolution',
    resourcesRequired: 'low',
    submitter: 'Ilana Smit',
    evaluator: 'Ilana Smit',
    impactScore: 3,
    createdAt: '2025-01-23T00:00:00Z'
  },
  {
    id: 15,
    title: 'Imagine citrus pre-made in a can / collaboration with Fitch and Leeds',
    description: 'Imagine citrus pre-made in a can / collaboration with Fitch and Leeds',
    status: 'under_review',
    department: 'Spirits',
    type: 'Product',
    strategy: 'Maintain Brand and Company image',
    workstation: 'Brandy',
    benefits: 'Creates new citrus product line through collaboration',
    resourcesRequired: 'medium',
    submitter: 'Petrus Eloff',
    evaluator: 'Ilse Du Toit',
    impactScore: 3,
    createdAt: '2025-01-13T00:00:00Z'
  },
  {
    id: 16,
    title: 'Change the current excel sheet that is used for lab analysis',
    description: 'Change the current excel sheet that is used for lab analysis to make capturing of samples easier and more efficient. Make a input page that writes all the date to a separate sheet that allows the user to just insert the date and not scroll up and down searching for the correct line and cell',
    status: 'approved',
    department: 'R&D',
    type: 'Improvement',
    strategy: 'Ensure SLA adherence',
    workstation: '',
    benefits: 'Improves lab analysis data capture efficiency',
    resourcesRequired: 'low',
    submitter: 'Grant Pietersen',
    evaluator: 'Lourens Stander',
    impactScore: 3,
    createdAt: '2025-03-06T00:00:00Z'
  },
  {
    id: 17,
    title: 'All Cans to be repacked on Moretta 2nd hand pallets only',
    description: 'All Cans to be repacked on Moretta 2nd hand pallets only',
    status: 'approved',
    department: 'Spirits',
    type: 'Improvement',
    strategy: 'Employ best practice',
    workstation: 'WAC',
    benefits: 'Standardizes can repacking on specific pallets',
    resourcesRequired: 'low',
    submitter: 'Garth Abrahams',
    evaluator: 'Garth Abrahams',
    impactScore: 3,
    createdAt: '2025-03-18T00:00:00Z'
  },
  {
    id: 18,
    title: 'Air pipe to be rolled up manually and stored in H12',
    description: 'Air pipe to be rolled up manually and stored in H12',
    status: 'approved',
    department: 'Spirits',
    type: 'Time saving',
    strategy: 'Employ best practice',
    workstation: 'WAC',
    benefits: 'Improves air pipe storage organization',
    resourcesRequired: 'low',
    submitter: 'Garth Abrahams',
    evaluator: 'Garth Abrahams',
    impactScore: 3,
    createdAt: '2025-03-18T00:00:00Z'
  },
  {
    id: 19,
    title: 'Install flowmeter on effluent line at J01 to Soyamoya',
    description: 'Install flowmeter on effluent line at J01 to Soyamoya',
    status: 'approved',
    department: 'Spirits',
    type: 'Improvement',
    strategy: 'Minimize waste',
    workstation: 'WAC',
    benefits: 'Monitors effluent flow for better waste management',
    resourcesRequired: 'low',
    submitter: 'Francois Joubert',
    evaluator: 'Francois Joubert',
    impactScore: 3,
    createdAt: '2025-03-18T00:00:00Z'
  },
  {
    id: 20,
    title: 'Barrier on road way to protected new loading platform',
    description: 'Barrier on road way to protected new loading platform',
    status: 'approved',
    department: 'Spirits',
    type: 'Safety',
    strategy: 'Minimize waste',
    workstation: 'Brandy',
    benefits: 'Enhances safety for new loading platform',
    resourcesRequired: 'low',
    submitter: 'Francois Joubert',
    evaluator: 'Francois Joubert',
    impactScore: 3,
    createdAt: '2025-03-18T00:00:00Z'
  },
  {
    id: 21,
    title: 'Counter weight for new platform stairs',
    description: 'Counter weight for new platform stairs',
    status: 'approved',
    department: 'Spirits',
    type: 'Safety',
    strategy: 'Employ best practice',
    workstation: 'Brandy',
    benefits: 'Improves safety of new platform stairs',
    resourcesRequired: 'low',
    submitter: 'Francois Joubert',
    evaluator: 'Francois Joubert',
    impactScore: 3,
    createdAt: '2025-03-18T00:00:00Z'
  },
  {
    id: 22,
    title: 'install temperature probes on the distillation warm water line',
    description: 'install temperature probes on the distillation warm water line to monitor the water temperature during distillation to ensure the dilution water is not too cold and to know when to apply more steam to the columns',
    status: 'approved',
    department: 'Logistics',
    type: 'Improvement',
    strategy: 'Ensure accuracy',
    workstation: '',
    benefits: 'Optimizes distillation process through temperature monitoring',
    resourcesRequired: 'low',
    submitter: 'Francois Filander',
    evaluator: 'Lourens Stander',
    impactScore: 3,
    createdAt: '2025-03-06T00:00:00Z'
  },
  {
    id: 23,
    title: 'Isolater at decanter conveyor',
    description: 'Isolater at decanter conveyor',
    status: 'approved',
    department: 'Logistics',
    type: 'Safety',
    strategy: 'Employ best practice',
    workstation: '',
    benefits: 'Enhances safety at decanter conveyor',
    resourcesRequired: 'low',
    submitter: 'Brian Plaatjies',
    evaluator: 'Francois Joubert',
    impactScore: 3,
    createdAt: '2025-03-18T00:00:00Z'
  },
  {
    id: 24,
    title: 'Reinforce water line from hydrant to decanter',
    description: 'Reinforce water line from hydrant to decanter',
    status: 'approved',
    department: 'Spirits',
    type: 'Safety',
    strategy: 'Minimize waste',
    workstation: 'Brandy',
    benefits: 'Improves water line safety and reliability',
    resourcesRequired: 'low',
    submitter: 'Brian Plaatjies',
    evaluator: 'Francois Joubert',
    impactScore: 3,
    createdAt: '2025-03-18T00:00:00Z'
  },
  {
    id: 25,
    title: 'To investigate the possibility of producing sugar-fermented alcoholic beverages',
    description: 'To investigate the possibility of producing sugar-fermented alcoholic beverages.  With the inclusion of beer products under the Liquor Products Act, one of the options to produce an alcoholic ferment from sugar + water + yeast should now be available for us.\nKWV could potentially utilise its fermentation facilities during the "off-season" to produce base for RTD-type products.  These should most likely fall under the 2203.00.90 SARS tariff - the same as our current HOOCH BLAST brand.',
    status: 'rejected',
    department: 'Spirits',
    type: 'Cost saving',
    strategy: 'Minimize cost',
    workstation: 'Brandy',
    benefits: 'Explores new product opportunities during off-season',
    resourcesRequired: 'high',
    submitter: 'Brian Grey',
    evaluator: 'Brian Grey',
    impactScore: 3,
    createdAt: '2025-03-18T00:00:00Z'
  },
  {
    id: 26,
    title: 'apply dosing panel @ WAC cooling tower to prevent bad water smells when starting up',
    description: 'apply dosing panel @ WAC cooling tower to prevent bad water smells when starting up',
    status: 'rejected',
    department: 'Spirits',
    type: 'Safety',
    strategy: 'Employ best practice',
    workstation: 'WAC',
    benefits: 'Prevents bad water smells at cooling tower startup',
    resourcesRequired: 'high',
    submitter: 'Ashwell Witbooi',
    evaluator: 'Ilse du Toit',
    impactScore: 3,
    createdAt: '2025-03-18T00:00:00Z'
  },
  {
    id: 27,
    title: 'Introducing a Disc Scanner where the weighbridge operator scans the Tankers disc',
    description: 'Introducing a Disc Scanner where the weighbridge operator scans the Tankers disc , driver licence and when scanning on the weighbridge computer the system fills all the information Automatic. There are variety of options that can be used, further consultation can be done, recommendation: Zebra MC9300 Series ( User manual Zebra MC9200 (English - 224 pages) )',
    status: 'under_review',
    department: 'Wine making',
    type: 'Improvement',
    strategy: 'Perform to world class standards',
    workstation: 'Viticulturist',
    benefits: 'Automates weighbridge data entry for improved efficiency',
    resourcesRequired: 'medium',
    submitter: 'Abie Kock',
    evaluator: 'Lourens Stander',
    impactScore: 3,
    createdAt: '2025-02-20T00:00:00Z'
  },
  {
    id: 28,
    title: 'Install a shutoff valve at the brandy distillery on the effluent line',
    description: 'Install a shutoff valve at the brandy distillery on the effluent line that is connected to a solenoid valve (that is already in place) . The alcohol % in the effluent is monitored with a Coriolis alcohol meter (already in place) with a siren (already in place) that indicates when an operator loses alcohol in the process. The valve can be connected to the solenoid that will close when alcohol is picked up and give the operator time to adjust the process and divert the alcohol to a tank and therefore not lose the alcohol.',
    status: 'approved',
    department: 'Wine making',
    type: 'Improvement',
    strategy: 'Minimize cost',
    workstation: 'Viticulturist',
    benefits: 'Prevents alcohol loss in effluent through automated shutoff',
    resourcesRequired: 'low',
    submitter: 'Andries Banda',
    evaluator: 'Lourens Stander',
    impactScore: 3,
    createdAt: '2025-02-20T00:00:00Z'
  },
  {
    id: 29,
    title: 'Develop an AI policy to prevent the unintended sharing or publishing of confidential company information',
    description: 'Develop an AI policy to prevent the unintended sharing or publishing of confidential company information',
    status: 'under_review',
    department: 'Wine making',
    type: 'Safety',
    strategy: 'Perform to world class standards',
    workstation: 'Viticulturist',
    benefits: 'Protects confidential information through AI policy',
    resourcesRequired: 'medium',
    submitter: 'Izanne de Wet & Kyle Willard',
    evaluator: 'Kyle Willard',
    impactScore: 3,
    createdAt: '2025-03-20T00:00:00Z'
  },
  {
    id: 30,
    title: 'labels for acids in the acid cupboard are on magnets so they can be moved when needed',
    description: 'labels for acids in the acid cupboard are on magnets so they can be moved when needed',
    status: 'approved',
    department: 'M&A',
    type: 'Improvement',
    strategy: 'Employ best practice',
    workstation: '',
    benefits: 'Improves acid cupboard labeling flexibility',
    resourcesRequired: 'low',
    submitter: 'Zelani Bellingan',
    evaluator: 'Kyle Willard',
    impactScore: 3,
    createdAt: '2025-03-20T00:00:00Z'
  },
  {
    id: 31,
    title: 'Purchase jumper cables for the laboratory golf',
    description: 'Purchase jumper cables for the laboratory golf',
    status: 'rejected',
    department: 'Quality',
    type: 'Safety',
    strategy: 'Continuously improve',
    workstation: 'Laboratory',
    benefits: 'Enables laboratory golf vehicle jump starting',
    resourcesRequired: 'high',
    submitter: 'Helana Brand',
    evaluator: 'Kyle Willard',
    impactScore: 3,
    createdAt: '2025-03-20T00:00:00Z'
  },
  {
    id: 32,
    title: 'Use stirrer from old conductivity meter for new conductivity meter',
    description: 'Use stirrer from old conductivity meter for new conductivity meter',
    status: 'approved',
    department: 'Quality',
    type: 'Improvement',
    strategy: 'Minimize waste',
    workstation: 'Laboratory',
    benefits: 'Repurposes old equipment to reduce waste',
    resourcesRequired: 'low',
    submitter: 'Rochelle Tempies',
    evaluator: 'Kyle Willard',
    impactScore: 3,
    createdAt: '2025-03-20T00:00:00Z'
  },
  {
    id: 33,
    title: 'Use Ciao as the harvest QC sample as it is more stable than the fortified wines',
    description: 'Use Ciao as the harvest QC sample as it is more stable than the fortified wines',
    status: 'approved',
    department: 'Quality',
    type: 'Improvement',
    strategy: 'Employ best practice',
    workstation: 'Laboratory',
    benefits: 'Improves QC sample stability for better quality control',
    resourcesRequired: 'low',
    submitter: 'Helana Brand',
    evaluator: 'Kyle Willard',
    impactScore: 3,
    createdAt: '2025-03-20T00:00:00Z'
  },
  {
    id: 34,
    title: 'Worcester deionised water system sometimes drips and this can  create a slipping risk',
    description: 'Worcester deionised water system sometimes drips and this can  create a slipping risk. A bucket was placed under the tap.',
    status: 'approved',
    department: 'Quality',
    type: 'Safety',
    strategy: 'Employ best practice',
    workstation: 'Laboratory',
    benefits: 'Reduces slipping risk from water system drips',
    resourcesRequired: 'low',
    submitter: 'Zelani Bellingan',
    evaluator: 'Kyle Willard',
    impactScore: 3,
    createdAt: '2025-03-20T00:00:00Z'
  },
  {
    id: 35,
    title: 'Equipment or dispensers that require repair or maintenance are put into specific work area',
    description: 'Equipment or dispensers that require repair or maintenance are put into specific work area with form to indicate what is not working.',
    status: 'approved',
    department: 'Quality',
    type: 'Improvement',
    strategy: 'Minimize waste',
    workstation: 'Laboratory',
    benefits: 'Improves equipment maintenance organization',
    resourcesRequired: 'low',
    submitter: 'Zelani Bellingan',
    evaluator: 'Kyle Willard',
    impactScore: 3,
    createdAt: '2025-03-20T00:00:00Z'
  },
  {
    id: 36,
    title: 'Two dispensers are rotated on the Fehling B chemical each month',
    description: 'Two dispensers are rotated on the Fehling B chemical each month to ensure there are not any sudden breakdowns',
    status: 'approved',
    department: 'Quality',
    type: 'Time saving',
    strategy: 'Employ best practice',
    workstation: 'Laboratory',
    benefits: 'Prevents dispenser breakdowns through rotation',
    resourcesRequired: 'low',
    submitter: 'Zelani Bellingan',
    evaluator: 'Kyle Willard',
    impactScore: 3,
    createdAt: '2025-03-20T00:00:00Z'
  },
  {
    id: 37,
    title: 'Relook at how the laboratory displays its MDWT board information',
    description: 'Relook at how the laboratory displays its MDWT board information to make it clearer',
    status: 'approved',
    department: 'Quality',
    type: 'Improvement',
    strategy: 'Employ best practice',
    workstation: 'Laboratory',
    benefits: 'Improves clarity of laboratory MDWT board information',
    resourcesRequired: 'low',
    submitter: 'Zelani Bellingan',
    evaluator: 'Kyle Willard',
    impactScore: 3,
    createdAt: '2025-03-20T00:00:00Z'
  },
  {
    id: 38,
    title: 'Implement a bar code on the asset stickers',
    description: 'Implement a bar code on the asset stickers to enable accurate inventory and physical check of the asset',
    status: 'under_review',
    department: 'Quality',
    type: 'Time saving',
    strategy: 'Employ best practice',
    workstation: 'Laboratory',
    benefits: 'Enables accurate asset inventory through barcode scanning',
    resourcesRequired: 'medium',
    submitter: 'Helana Brand',
    evaluator: 'Kyle Willard',
    impactScore: 3,
    createdAt: '2025-03-20T00:00:00Z'
  },
  {
    id: 39,
    title: 'Rinse milkoscan waste pipe with hot water and soap weekly',
    description: 'Rinse milkoscan waste pipe with hot water and soap weekly to melt fat and prevent microbial growth',
    status: 'approved',
    department: 'Quality',
    type: 'Time saving',
    strategy: 'Employ best practice',
    workstation: 'Laboratory',
    benefits: 'Prevents microbial growth in milkoscan waste pipe',
    resourcesRequired: 'low',
    submitter: 'Sandra de Villiers',
    evaluator: 'Kyle Willard',
    impactScore: 3,
    createdAt: '2025-03-20T00:00:00Z'
  },
  {
    id: 40,
    title: 'HR survey responses do not provide alot of information',
    description: 'HR survey responses do not provide alot of information. The suggestion is to turn the feedback into an infographic with generalised information to enable us to see where we fall and where the rest of the company is falling.',
    status: 'under_review',
    department: 'Quality',
    type: 'Improvement',
    strategy: 'Ensure continuous feedback and communication',
    workstation: 'Laboratory',
    benefits: 'Improves HR survey feedback visualization through infographics',
    resourcesRequired: 'medium',
    submitter: 'Zelani Bellingan',
    evaluator: 'Kyle Willard',
    impactScore: 3,
    createdAt: '2025-03-20T00:00:00Z'
  },
  {
    id: 41,
    title: 'Make a media control sheet to mount on fridge in the micro lab',
    description: 'Make a media control sheet to mount on fridge in the micro lab with expiry dates\n',
    status: 'approved',
    department: 'Quality',
    type: 'Time saving',
    strategy: 'Employ best practice',
    workstation: 'Laboratory',
    benefits: 'Improves media expiry tracking in micro lab',
    resourcesRequired: 'low',
    submitter: 'Letitia Nadasen',
    evaluator: 'Kyle Willard',
    impactScore: 3,
    createdAt: '2025-03-20T00:00:00Z'
  },
  {
    id: 42,
    title: 'Use a piece of filter sheet to stand beakers that have been in the glycol bath',
    description: 'Use a piece of filter sheet to stand beakers that have been in the glycol bath to reduce the mess',
    status: 'approved',
    department: 'Quality',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: 'Laboratory',
    benefits: 'Reduces mess from glycol bath beakers',
    resourcesRequired: 'low',
    submitter: 'Rochelle Tempies',
    evaluator: 'Kyle Willard',
    impactScore: 3,
    createdAt: '2025-03-20T00:00:00Z'
  },
  {
    id: 43,
    title: 'The bug bottles emptied in the laboratory are put into a cardboard box',
    description: 'The bug bottles emptied in the laboratory are put into a cardboard box, a piece of filter sheet is put at the bottle to prevent any spillage from reducing the boxes structural integrity and it tearing when the box is moved.',
    status: 'approved',
    department: 'Quality',
    type: 'Improvement',
    strategy: 'Employ best practice',
    workstation: 'Laboratory',
    benefits: 'Improves bug bottle disposal safety and organization',
    resourcesRequired: 'low',
    submitter: 'Rochelle Tempies',
    evaluator: 'Kyle Willard',
    impactScore: 3,
    createdAt: '2025-03-20T00:00:00Z'
  },
  {
    id: 44,
    title: 'A colony identification chart for micro medias added to the table',
    description: 'A colony identification chart for micro medias added to the table for quick visual reference',
    status: 'approved',
    department: 'Quality',
    type: 'Time saving',
    strategy: 'Employ best practice',
    workstation: 'Laboratory',
    benefits: 'Enables quick colony identification through visual reference',
    resourcesRequired: 'low',
    submitter: 'Zelani Bellingan',
    evaluator: 'Kyle Willard',
    impactScore: 3,
    createdAt: '2025-03-20T00:00:00Z'
  },
  {
    id: 45,
    title: 'Create a table with instructions how to operate machine/prep',
    description: 'Create a table with instructions how to operate machine/prep , placed on instrument for the different samples received by the Worcester laboratory for analysis on the Alcolyser',
    status: 'approved',
    department: 'Quality',
    type: 'Time saving',
    strategy: 'Ensure accuracy',
    workstation: 'Laboratory',
    benefits: 'Improves Alcolyser operation accuracy through clear instructions',
    resourcesRequired: 'low',
    submitter: 'Zelani Bellingan',
    evaluator: 'Kyle Willard',
    impactScore: 3,
    createdAt: '2025-03-20T00:00:00Z'
  },
  {
    id: 46,
    title: 'Stylus for touch screens on the pH instruments',
    description: 'Stylus for touch screens on the pH instruments',
    status: 'approved',
    department: 'Quality',
    type: 'Improvement',
    strategy: 'Employ best practice',
    workstation: 'Laboratory',
    benefits: 'Improves pH instrument touchscreen operation',
    resourcesRequired: 'low',
    submitter: 'Anthea Johnson',
    evaluator: 'Kyle Willard',
    impactScore: 3,
    createdAt: '2025-03-20T00:00:00Z'
  },
  {
    id: 47,
    title: 'When saving the Botanicals COAs, I put the Mat code in name',
    description: 'When saving the Botanicals COAs, I put the Mat code in name, for easy reference.',
    status: 'approved',
    department: 'Quality',
    type: 'Time saving',
    strategy: 'Ensure responsiveness and urgency',
    workstation: 'Laboratory',
    benefits: 'Improves Botanicals COA file organization through Mat code naming',
    resourcesRequired: 'low',
    submitter: 'Suzanne Long',
    evaluator: 'Petrus Eloff',
    impactScore: 3,
    createdAt: '2025-03-20T00:00:00Z'
  },
  {
    id: 48,
    title: 'Cap for winescan tubes - reduce alcohol loss and improve accuracy (3D printed)',
    description: 'Cap for winescan tubes - reduce alcohol loss and improve accuracy (3D printed)',
    status: 'approved',
    department: 'Spirits',
    type: 'Improvement',
    strategy: 'Ensure accuracy',
    workstation: 'Brandy',
    benefits: 'Reduces alcohol loss and improves accuracy with 3D printed caps',
    resourcesRequired: 'low',
    submitter: 'Kyle Willard',
    evaluator: 'Kyle Willard',
    impactScore: 3,
    createdAt: '2025-04-10T00:00:00Z'
  },
  {
    id: 49,
    title: 'Tie for harvest & weighbridge pH / TA titrators to keep pH probe away from stirrer',
    description: 'Tie for harvest & weighbridge pH / TA titrators to keep pH probe away from stirrer to prevent skins being trapped and affecting results (3D Printed)',
    status: 'approved',
    department: 'Quality',
    type: 'Improvement',
    strategy: 'Ensure accuracy',
    workstation: 'Laboratory',
    benefits: 'Improves pH/TA titration accuracy through 3D printed ties',
    resourcesRequired: 'low',
    submitter: 'Kyle Willard',
    evaluator: 'Kyle Willard',
    impactScore: 3,
    createdAt: '2025-04-10T00:00:00Z'
  },
  {
    id: 50,
    title: 'Install an antifoam dosing pump (timer based) on the water make-up line of C10 cooling tower',
    description: 'Install an antifoam dosing pump (timer based) on the water make-up line of C10 cooling tower to prevent excessive foaming.',
    status: 'approved',
    department: 'Quality',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: 'Laboratory',
    benefits: 'Prevents excessive foaming in cooling tower through dosing pump',
    resourcesRequired: 'low',
    submitter: 'Andries Banda',
    evaluator: 'Clarence McClune',
    impactScore: 3,
    createdAt: '2025-04-16T00:00:00Z'
  },
  {
    id: 51,
    title: 'Modify the line of the Viking Oil pull off',
    description: 'Modify the line of the Viking Oil pull off so that it will run straight downwards to the tank, instead of the current line that is running upwards, above the pull off point height, before it goes to the tank.',
    status: 'approved',
    department: 'Spirits',
    type: 'Product',
    strategy: 'Continuously improve',
    workstation: 'Worcester',
    benefits: 'Improves Viking Oil pull off efficiency through line modification',
    resourcesRequired: 'low',
    submitter: 'Clarence McClune',
    evaluator: 'Clarence McClune',
    impactScore: 3,
    createdAt: '2025-05-14T00:00:00Z'
  },
  {
    id: 52,
    title: 'Call Center to halt on use of paper for order checking, all via PDF',
    description: 'Call Center to halt on use of paper for order checking, all via PDF',
    status: 'approved',
    department: 'Spirits',
    type: 'Cost saving',
    strategy: 'Minimize waste',
    workstation: '',
    benefits: 'Reduces paper usage in call center through PDF order checking',
    resourcesRequired: 'low',
    submitter: 'James Reade-Jahn',
    evaluator: 'James Reade-Jahn',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 53,
    title: 'Monitoring Allocations versus blocked orders - if no stock dont save order',
    description: 'Monitoring Allocations versus blocked orders - if no stock dont save order',
    status: 'approved',
    department: 'Logistics',
    type: 'Improvement',
    strategy: 'Deliver on customer expectation',
    workstation: '',
    benefits: 'Prevents order saving when no stock available',
    resourcesRequired: 'low',
    submitter: 'Loyiso Ngxazana',
    evaluator: 'James Reade-Jahn',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 54,
    title: 'Acquired new COT stand',
    description: 'Acquired new COT stand',
    status: 'approved',
    department: 'Logistics',
    type: 'Improvement',
    strategy: 'Employ best practice',
    workstation: '',
    benefits: 'Provides new COT stand for improved operations',
    resourcesRequired: 'low',
    submitter: 'Harold Bailey',
    evaluator: 'Harold Bailey',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 55,
    title: 'Modified old COT stand',
    description: 'Modified old COT stand',
    status: 'approved',
    department: 'Wine making',
    type: 'Improvement',
    strategy: 'Employ best practice',
    workstation: 'Pre-bottling',
    benefits: 'Improves old COT stand through modification',
    resourcesRequired: 'low',
    submitter: 'Harold Bailey',
    evaluator: 'Harold Bailey',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 56,
    title: 'Made bracket for locking of chemicals to prevent any tampering',
    description: 'Made bracket for locking of chemicals to prevent any tampering.',
    status: 'approved',
    department: 'Wine making',
    type: 'Safety',
    strategy: 'Employ best practice',
    workstation: 'Pre-bottling',
    benefits: 'Enhances chemical security through locking bracket',
    resourcesRequired: 'low',
    submitter: 'Harold Bailey',
    evaluator: 'Harold Bailey',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 57,
    title: 'Extend water hoses to top of tanks for proper cleaning',
    description: 'Extend water hoses to top of tanks for proper cleaning on top of tanks',
    status: 'approved',
    department: 'Wine making',
    type: 'Improvement',
    strategy: 'Perform to world class standards',
    workstation: 'Pre-bottling',
    benefits: 'Improves tank cleaning efficiency through extended hoses',
    resourcesRequired: 'low',
    submitter: 'Harold Bailey',
    evaluator: 'Harold Bailey',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 58,
    title: 'Make use of pH strips to verify pH of water after sterilisation',
    description: 'Make use of pH strips to verify pH of water after sterilisation.',
    status: 'approved',
    department: 'Wine making',
    type: 'Time saving',
    strategy: 'Employ best practice',
    workstation: 'Pre-bottling',
    benefits: 'Verifies water pH after sterilization through pH strips',
    resourcesRequired: 'low',
    submitter: 'Harold Bailey',
    evaluator: 'Harold Bailey',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 59,
    title: 'Made signage poster for WIP to prevent tampering',
    description: 'Made signage poster for WIP to prevent tampering',
    status: 'approved',
    department: 'Wine making',
    type: 'Safety',
    strategy: 'Continuously improve',
    workstation: 'Pre-bottling',
    benefits: 'Prevents WIP tampering through signage',
    resourcesRequired: 'low',
    submitter: 'Harold Bailey',
    evaluator: 'Harold Bailey',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 60,
    title: 'Grids for A07 store',
    description: 'Grids for A07 store',
    status: 'approved',
    department: 'Wine making',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: 'Pre-bottling',
    benefits: 'Organizes A07 store through grid system',
    resourcesRequired: 'low',
    submitter: 'Anthony Juries',
    evaluator: 'Anthony Juries ',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 61,
    title: 'Design washer for flex tanks',
    description: 'Design washer for flex tanks',
    status: 'approved',
    department: 'Wine making',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: 'Red',
    benefits: 'Improves flex tank cleaning through designed washer',
    resourcesRequired: 'low',
    submitter: 'Anthony Juries',
    evaluator: 'Anthony Juries',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 62,
    title: 'Design NW T-piece',
    description: 'Design NW T-piece',
    status: 'rejected',
    department: 'Wine making',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: 'Red',
    benefits: 'Improves system connectivity through NW T-piece design',
    resourcesRequired: 'high',
    submitter: 'Anthony Juries',
    evaluator: 'Anthony Juries',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 63,
    title: 'Catwalk for A6 between tanks 68  71 , 28  32',
    description: 'Catwalk for A6 between tanks 68  71 , 28  32',
    status: 'rejected',
    department: 'Wine making',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: 'Red',
    benefits: 'Improves access between tanks through catwalk installation',
    resourcesRequired: 'high',
    submitter: 'Anthony Juries',
    evaluator: 'Anthony Juries',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 64,
    title: 'Stacking lines in A4A',
    description: 'Stacking lines in A4A',
    status: 'approved',
    department: 'Wine making',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: 'Red',
    benefits: 'Improves organization in A4A through stacking lines',
    resourcesRequired: 'low',
    submitter: 'Anthony Juries',
    evaluator: 'Anthony Juries',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 65,
    title: 'Design fixed pumps on A07 tanks to be used for pump overs also',
    description: 'Design fixed pumps on A07 tanks to be used for pump overs also',
    status: 'approved',
    department: 'Wine making',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: 'Red',
    benefits: 'Enhances pump over efficiency through fixed pump design',
    resourcesRequired: 'low',
    submitter: 'Anthony Juries',
    evaluator: 'Anthony Juries',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 66,
    title: 'Warm water line for A05',
    description: 'Warm water line for A05',
    status: 'rejected',
    department: 'Wine making',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: 'Red',
    benefits: 'Provides warm water access for A05 operations',
    resourcesRequired: 'high',
    submitter: 'Anthony Juries',
    evaluator: 'Anthony Juries',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 67,
    title: 'Design washer for A05 tanks',
    description: 'Design washer for A05 tanks',
    status: 'rejected',
    department: 'Wine making',
    type: 'Improvement',
    strategy: 'Employ best practice',
    workstation: 'Red',
    benefits: 'Improves A05 tank cleaning through designed washer',
    resourcesRequired: 'high',
    submitter: 'Anthony Juries',
    evaluator: 'Anthony Juries',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 68,
    title: 'Add extra valves on all Fixed lines for pressure release',
    description: 'Add extra valves on all Fixed lines for pressure release',
    status: 'rejected',
    department: 'Wine making',
    type: 'Improvement',
    strategy: 'Minimize waste',
    workstation: 'Red',
    benefits: 'Improves safety through pressure release valves',
    resourcesRequired: 'high',
    submitter: 'Anthony Juries',
    evaluator: 'Anthony Juries',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 69,
    title: 'Cover for buckets to keep dry ice in buckets',
    description: 'Cover for buckets to keep dry ice in buckets',
    status: 'approved',
    department: 'Wine making',
    type: 'Safety',
    strategy: 'Minimize waste',
    workstation: 'Red',
    benefits: 'Maintains dry ice effectiveness through bucket covers',
    resourcesRequired: 'low',
    submitter: 'Anthony Juries',
    evaluator: 'Anthony Juries',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 70,
    title: 'Add fixed line in A05 for wine transfers',
    description: 'Add fixed line in A05 for wine transfers.',
    status: 'rejected',
    department: 'Wine making',
    type: 'Time saving',
    strategy: 'Continuously improve',
    workstation: 'Red',
    benefits: 'Improves wine transfer efficiency through fixed line',
    resourcesRequired: 'high',
    submitter: 'Anthony Juries',
    evaluator: 'Anthony Juries',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 71,
    title: 'Add extra plugs to replace extension cord',
    description: 'Add extra plugs to replace extension cord',
    status: 'rejected',
    department: 'Wine making',
    type: 'Improvement',
    strategy: 'Employ best practice',
    workstation: 'Red',
    benefits: 'Improves electrical safety through additional plugs',
    resourcesRequired: 'high',
    submitter: 'Anthony Juries',
    evaluator: 'Anthony Juries',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 72,
    title: 'Add extra water taps to replace 15m water pipes',
    description: 'Add extra water taps to replace 15m water pipes',
    status: 'rejected',
    department: 'Wine making',
    type: 'Time saving',
    strategy: 'Continuously improve',
    workstation: 'Red',
    benefits: 'Improves water access efficiency through additional taps',
    resourcesRequired: 'high',
    submitter: 'Anthony Juries',
    evaluator: 'Anthony Juries',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 73,
    title: 'Install fire extinguisher diesel trailer',
    description: 'Install fire extinguisher diesel trailer',
    status: 'approved',
    department: 'Wine making',
    type: 'Safety',
    strategy: 'Employ best practice',
    workstation: 'Red',
    benefits: 'Enhances fire safety through diesel trailer extinguisher',
    resourcesRequired: 'low',
    submitter: 'Francois Joubert',
    evaluator: 'Francois Joubert ',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 74,
    title: 'C14 2 way system with 3 phase female plug for low pumps',
    description: 'C14 2 way system with 3 phase female plug for low pumps',
    status: 'approved',
    department: 'Spirits',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: 'Worcester',
    benefits: 'Improves low pump connectivity through C14 2 way system',
    resourcesRequired: 'low',
    submitter: 'Shorne Horne',
    evaluator: 'Francois Joubert  ',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 75,
    title: 'New stair and platform for H camp',
    description: 'New stair and platform for H camp',
    status: 'approved',
    department: 'Spirits',
    type: 'Safety',
    strategy: 'Continuously improve',
    workstation: 'Worcester',
    benefits: 'Enhances H camp safety through new stair and platform',
    resourcesRequired: 'low',
    submitter: 'Francois Joubert',
    evaluator: 'Francois Joubert',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 76,
    title: 'Improve explosions proof lights at H10',
    description: 'Improve explosions proof lights at H10',
    status: 'approved',
    department: 'Spirits',
    type: 'Safety',
    strategy: 'Employ best practice',
    workstation: 'Worcester',
    benefits: 'Enhances safety at H10 through improved explosion proof lights',
    resourcesRequired: 'low',
    submitter: 'Francois Joubert',
    evaluator: 'Francois Joubert',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 77,
    title: 'Install extra down pipes at H02,H03 and H04 to prevent flooding in stores',
    description: 'Install extra down pipes at H02,H03 and H04 to prevent flooding in stores',
    status: 'approved',
    department: 'Spirits',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: 'Worcester',
    benefits: 'Prevents store flooding through additional down pipes',
    resourcesRequired: 'low',
    submitter: 'Francois Joubert',
    evaluator: 'Francois Joubert',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 78,
    title: 'Improve water meter barrier at alcohol sale store',
    description: 'Improve water meter barrier at alcohol sale store',
    status: 'approved',
    department: 'Spirits',
    type: 'Improvement',
    strategy: 'Ensure accuracy',
    workstation: 'Worcester',
    benefits: 'Improves water meter accuracy at alcohol sale store',
    resourcesRequired: 'low',
    submitter: 'Francois Joubert',
    evaluator: 'Francois Joubert',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 79,
    title: 'Install new water meter barrier lid for protection',
    description: 'Install new water meter barrier lid for protection',
    status: 'approved',
    department: 'Spirits',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: 'Worcester',
    benefits: 'Protects water meter through new barrier lid',
    resourcesRequired: 'low',
    submitter: 'Francois Joubert',
    evaluator: 'Francois Joubert ',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 80,
    title: 'As our clients place orders for bulk collection, I send them our operating hours',
    description: 'As our clients place orders for bulk collection, I send them our operating hours, therefore I neednt let them know every time, they are informed & they have it on record',
    status: 'approved',
    department: 'Spirits',
    type: 'Improvement',
    strategy: 'Deliver on customer expectation',
    workstation: 'Worcester',
    benefits: 'Improves customer communication through operating hours documentation',
    resourcesRequired: 'low',
    submitter: 'Suzanne Long',
    evaluator: 'Suzanne Long ',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 81,
    title: 'KA upliftments linked via repforce with RSM approvals',
    description: 'KA upliftments linked via repforce with RSM approvals',
    status: 'approved',
    department: 'Spirits',
    type: 'Time saving',
    strategy: 'Ensure continuous feedback and communication',
    workstation: 'Brandy',
    benefits: 'Streamlines KA upliftments through repforce integration',
    resourcesRequired: 'low',
    submitter: 'James Reade-Jahn & Bornatius Schroeder',
    evaluator: 'James Reade-Jahn',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 82,
    title: 'Call Centre Monthly reporting dashboard',
    description: 'Call Centre Monthly reporting dashboard',
    status: 'approved',
    department: 'Logistics',
    type: 'Improvement',
    strategy: 'Employ best practice',
    workstation: '',
    benefits: 'Improves call center reporting through monthly dashboard',
    resourcesRequired: 'low',
    submitter: 'James Reade-Jahn',
    evaluator: 'James Reade-Jahn',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 83,
    title: 'Makro booking confirmations procedure',
    description: 'Makro booking confirmations procedure',
    status: 'approved',
    department: 'Logistics',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: '',
    benefits: 'Standardizes Makro booking confirmations through procedure',
    resourcesRequired: 'low',
    submitter: 'James Reade-Jahn & Eugene Roux',
    evaluator: 'James Reade-Jahn',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 84,
    title: 'SAB order management Procedure',
    description: 'SAB order management Procedure',
    status: 'approved',
    department: 'Logistics',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: '',
    benefits: 'Improves SAB order management through standardized procedure',
    resourcesRequired: 'low',
    submitter: 'Eugene Roux',
    evaluator: 'James Reade-Jahn',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 85,
    title: 'Bulk order management procedure',
    description: 'Bulk order management procedure',
    status: 'approved',
    department: 'Logistics',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: '',
    benefits: 'Standardizes bulk order management through procedure',
    resourcesRequired: 'low',
    submitter: 'Eugene Roux',
    evaluator: 'James Reade-Jahn',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 86,
    title: 'Staff & promo stock procedure',
    description: 'Staff & promo stock procedure',
    status: 'approved',
    department: 'Logistics',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: '',
    benefits: 'Streamlines management of staff and promotional stock',
    resourcesRequired: 'low',
    submitter: 'James Reade-Jahn',
    evaluator: 'James Reade-Jahn',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 87,
    title: 'A developed plan for selling international risk stock to SA B2B customers',
    description: 'A developed plan for selling international risk stock to SA B2B customers.',
    status: 'approved',
    department: 'Logistics',
    type: 'Cost saving',
    strategy: 'Minimize waste',
    workstation: '',
    benefits: 'Optimizes international risk stock through SA B2B sales plan',
    resourcesRequired: 'low',
    submitter: 'James Reade-Jahn',
    evaluator: 'James Reade-Jahn',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 88,
    title: 'Region indicator coded into SAP vl10a for order processing',
    description: 'Region indicator coded into SAP vl10a for order processing',
    status: 'approved',
    department: 'Logistics',
    type: 'Improvement',
    strategy: 'Ensure accuracy',
    workstation: '',
    benefits: 'Improves order processing accuracy through SAP region coding',
    resourcesRequired: 'low',
    submitter: 'James Reade-Jahn',
    evaluator: 'James Reade-Jahn',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 89,
    title: 'I would like to propose an enhancement to our employee incentive',
    description: 'I would like to propose an enhancement to our employee incentive , by requesting a more inclusive  appreciated option for employees to choose between receiving a box of alcohol , or a food voucher to the value of the box , as our year end incentive for hard work.',
    status: 'under_review',
    department: 'Logistics',
    type: 'Other',
    strategy: 'Continuously improve',
    workstation: '',
    benefits: 'Enhances employee incentive options through choice of rewards',
    resourcesRequired: 'medium',
    submitter: 'A Johnson',
    evaluator: 'K Willard',
    impactScore: 3,
    createdAt: '2025-05-26T00:00:00Z'
  },
  {
    id: 90,
    title: 'Township or underrepresented communities wine tasting experience',
    description: 'Township or underrepresented communities wine tasting experience:\nIntroduce wine pairing with the one thing South Africans love, braai. What wine goes with what meat on the braai? Organise a braai, do the wine pairing and get a tik-tok influencer or local musician involved perhaps.\n',
    status: 'under_review',
    department: 'Quality',
    type: 'Other',
    strategy: 'Continuously improve',
    workstation: 'Laboratory',
    benefits: 'Expands market reach through community wine tasting experiences',
    resourcesRequired: 'medium',
    submitter: 'Isaac Moosa',
    evaluator: 'Frikkie van der Walt',
    impactScore: 3,
    createdAt: '2025-07-07T00:00:00Z'
  },
  {
    id: 91,
    title: 'Reusable packaging to stay in-line with our sustainability value',
    description: 'Reusable packaging to stay in-line with our sustainability value: include oil or vinegar pourers as part of a reusable packaging & bottle recycling for mechendise',
    status: 'under_review',
    department: 'Technical',
    type: 'Cost saving',
    strategy: 'Deliver on customer expectation',
    workstation: '',
    benefits: 'Supports sustainability through reusable packaging initiatives',
    resourcesRequired: 'medium',
    submitter: 'Isaac Moosa',
    evaluator: 'Frikkie van der Walt',
    impactScore: 3,
    createdAt: '2025-07-07T00:00:00Z'
  },
  {
    id: 92,
    title: 'Put a good quality, everyday drinking wine in a 250ml carton',
    description: 'Put a good quality, everyday drinking wine in a 250ml carton. Almost like the long-life milk carton, but just smaller. To draw attention from townships, where our focus should be, incorporate art or graffiti from a local township artist on the 250ml carton. Even better, organise a drawing or graffiti competition. The winners design will display on the carton. The community will feel a part of the production of the product.',
    status: 'under_review',
    department: 'Technical',
    type: 'Product',
    strategy: 'Continuously improve',
    workstation: '',
    benefits: 'Creates accessible product for township markets through 250ml carton',
    resourcesRequired: 'medium',
    submitter: 'Isaac Moosa',
    evaluator: 'Frikkie van der Walt',
    impactScore: 3,
    createdAt: '2025-07-07T00:00:00Z'
  },
  {
    id: 93,
    title: 'Introduce a reward system for buying through our mobile app',
    description: 'Introduce a reward system for buying through our mobile app. Rewards could include free airtime, product or even merchandise like KWV caps or mugs or T-shirts.',
    status: 'under_review',
    department: 'Technical',
    type: 'Other',
    strategy: 'Deliver on customer expectation',
    workstation: '',
    benefits: 'Encourages mobile app usage through reward system',
    resourcesRequired: 'medium',
    submitter: 'Isaac Moosa',
    evaluator: 'Frikkie van der Walt',
    impactScore: 3,
    createdAt: '2025-07-07T00:00:00Z'
  },
  {
    id: 94,
    title: 'Staff leave booked as a calendar item for managers and colleagues',
    description: 'Staff leave booked as a calendar item for managers and colleagues to provide visibility about who is on leave when',
    status: 'approved',
    department: 'Technical',
    type: 'Improvement',
    strategy: 'Ensure continuous feedback and communication',
    workstation: '',
    benefits: 'Improves leave visibility through calendar integration',
    resourcesRequired: 'low',
    submitter: 'Suzanne Long',
    evaluator: 'Ilse du Toit',
    impactScore: 3,
    createdAt: '2025-07-07T00:00:00Z'
  },
  {
    id: 95,
    title: 'S/S cover for HMI screen on polymer station',
    description: 'S/S cover for HMI screen on polymer station',
    status: 'approved',
    department: 'Spirits',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: 'Brandy',
    benefits: 'Protects HMI screen on polymer station through S/S cover',
    resourcesRequired: 'low',
    submitter: 'Francois Joubert',
    evaluator: 'Francois Joubert',
    impactScore: 3,
    createdAt: '2025-07-07T00:00:00Z'
  },
  {
    id: 96,
    title: 'Safety barrier at C10 exit door',
    description: 'Safety barrier at C10 exit door',
    status: 'approved',
    department: 'Spirits',
    type: 'Safety',
    strategy: 'Continuously improve',
    workstation: 'Worcester',
    benefits: 'Enhances safety at C10 exit door through barrier installation',
    resourcesRequired: 'low',
    submitter: 'Francois Joubert',
    evaluator: 'Francois Joubert',
    impactScore: 3,
    createdAt: '2025-07-08T00:00:00Z'
  },
  {
    id: 97,
    title: 'Reinforce supply line to decanter',
    description: 'Reinforce supply line to decanter',
    status: 'approved',
    department: 'Spirits',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: 'Worcester',
    benefits: 'Improves decanter supply line reliability through reinforcement',
    resourcesRequired: 'low',
    submitter: 'Francois Joubert',
    evaluator: 'Francois Joubert',
    impactScore: 3,
    createdAt: '2025-07-08T00:00:00Z'
  },
  {
    id: 98,
    title: 'Upgrade DB boards at T47,T48 & T49 install additional shut off Breakers',
    description: 'Upgrade DB boards at T47,T48 & T49 install additional shut off Breakers',
    status: 'approved',
    department: 'Spirits',
    type: 'Safety',
    strategy: 'Employ best practice',
    workstation: 'Worcester',
    benefits: 'Enhances electrical safety through DB board upgrades',
    resourcesRequired: 'low',
    submitter: 'Francois Joubert',
    evaluator: 'Francois Joubert',
    impactScore: 3,
    createdAt: '2025-07-08T00:00:00Z'
  },
  {
    id: 99,
    title: 'Install phosphor brass  bushes on hanger to prolong life span',
    description: 'Install phosphor brass  bushes on hanger to prolong life span',
    status: 'approved',
    department: 'Spirits',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: 'Worcester',
    benefits: 'Extends hanger lifespan through phosphor brass bushes',
    resourcesRequired: 'low',
    submitter: 'Francois Joubert',
    evaluator: 'Francois Joubert  ',
    impactScore: 3,
    createdAt: '2025-07-08T00:00:00Z'
  },
  {
    id: 100,
    title: 'Demarcation of canteens and toilets',
    description: 'Demarcation of canteens and toilets',
    status: 'approved',
    department: 'Spirits',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: 'Worcester',
    benefits: 'Improves facility organization through clear demarcation',
    resourcesRequired: 'low',
    submitter: 'Brian Plaatjies',
    evaluator: 'Francois Joubert',
    impactScore: 3,
    createdAt: '2025-07-08T00:00:00Z'
  },
  {
    id: 101,
    title: 'Extent condensate vent pipe  at C10 to ground level',
    description: 'Extent condensate vent pipe  at C10 to ground level',
    status: 'approved',
    department: 'Spirits',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: 'Worcester',
    benefits: 'Improves condensate vent pipe accessibility at ground level',
    resourcesRequired: 'low',
    submitter: 'Francois Joubert',
    evaluator: 'Francois Joubert',
    impactScore: 3,
    createdAt: '2025-07-08T00:00:00Z'
  },
  {
    id: 102,
    title: 'Replace lights on site with cost saving lights  from Econ led',
    description: 'Replace lights on site with cost saving lights  from Econ led',
    status: 'approved',
    department: 'Spirits',
    type: 'Safety',
    strategy: 'Minimize waste',
    workstation: 'Worcester',
    benefits: 'Reduces energy costs through LED light replacement',
    resourcesRequired: 'low',
    submitter: 'Francois Joubert',
    evaluator: 'Francois Joubert',
    impactScore: 3,
    createdAt: '2025-07-08T00:00:00Z'
  },
  {
    id: 103,
    title: 'Replace old black wine balls with red food grade wine ball on piston pump',
    description: 'Replace old black wine balls with red food grade wine ball on piston pump',
    status: 'approved',
    department: 'Spirits',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: 'Worcester',
    benefits: 'Improves piston pump safety through food grade wine balls',
    resourcesRequired: 'low',
    submitter: 'Brain Plaatjies',
    evaluator: 'Francois Joubert',
    impactScore: 3,
    createdAt: '2025-07-08T00:00:00Z'
  },
  {
    id: 104,
    title: 'Create brackets from old redundant material to hang equipment',
    description: 'Create brackets from old redundant material to hang equipment',
    status: 'approved',
    department: 'Spirits',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: 'Worcester',
    benefits: 'Repurposes old materials for equipment organization',
    resourcesRequired: 'low',
    submitter: 'Francois Joubert',
    evaluator: 'Francois Joubert',
    impactScore: 3,
    createdAt: '2025-07-08T00:00:00Z'
  },
  {
    id: 105,
    title: 'Additional staircase over ash conveyor between Boiler 2 and Boiler 3',
    description: 'Additional staircase over ash conveyor between Boiler 2 and Boiler 3',
    status: 'approved',
    department: 'Spirits',
    type: 'Safety',
    strategy: 'Continuously improve',
    workstation: 'Worcester',
    benefits: 'Enhances safety access between boilers through additional staircase',
    resourcesRequired: 'low',
    submitter: 'Francois Joubert',
    evaluator: 'Francois Joubert',
    impactScore: 3,
    createdAt: '2025-07-08T00:00:00Z'
  },
  {
    id: 106,
    title: 'Coloured sample crates for every cellar to take samples to the lab',
    description: '1. Coloured sample crates for every cellar to take samples to the lab\na. Make it easier to carry to the lab\nb. Samples would already be packed in sequence of lab list',
    status: 'rejected',
    department: 'Spirits',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: 'Worcester',
    benefits: 'Improves sample transport efficiency through colored crates',
    resourcesRequired: 'high',
    submitter: 'Izele van Blerk',
    evaluator: 'Izele van Blerk',
    impactScore: 3,
    createdAt: '2025-07-08T00:00:00Z'
  },
  {
    id: 107,
    title: 'Tank numbers on top of Fermentation tanks in Mentors Cellar',
    description: '2. Tank numbers on top of Fermentation tanks in Mentors Cellar\na. Make it easier to double check tank numbers for pumpovers',
    status: 'approved',
    department: 'Wine making',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: 'Mentors',
    benefits: 'Improves tank identification in Mentors Cellar',
    resourcesRequired: 'low',
    submitter: 'Izele van Blerk',
    evaluator: 'Izele van Blerk',
    impactScore: 3,
    createdAt: '2025-07-08T00:00:00Z'
  },
  {
    id: 108,
    title: 'e-use of routine samples bottles  cellar team to collect sample bottles from lab',
    description: 'e-use of routine samples bottles  cellar team to collect sample bottles from lab every 2nd day, to clean and re-use, would be a cost saving',
    status: 'rejected',
    department: 'Wine making',
    type: 'Cost saving',
    strategy: 'Minimize waste',
    workstation: 'Mentors',
    benefits: 'Reduces costs through sample bottle reuse program',
    resourcesRequired: 'high',
    submitter: 'Izele van Blerk',
    evaluator: 'Izele van Blerk',
    impactScore: 3,
    createdAt: '2025-07-08T00:00:00Z'
  },
  {
    id: 109,
    title: 'More fixed lines for pumpovers  in Mentors cellar, time saving  and safety',
    description: 'More fixed lines for pumpovers  in Mentors cellar, time saving  and safety',
    status: 'rejected',
    department: 'Wine making',
    type: 'Improvement',
    strategy: 'Minimize waste',
    workstation: 'Mentors',
    benefits: 'Improves pumpover efficiency and safety through fixed lines',
    resourcesRequired: 'high',
    submitter: 'Izele van Blerk',
    evaluator: 'Izele van Blerk',
    impactScore: 3,
    createdAt: '2025-07-08T00:00:00Z'
  },
  {
    id: 110,
    title: 'Extend leads of controls on mono-pumps in Mentors cellar',
    description: 'Extend leads of controls on mono-pumps in Mentors cellar  better control to fill barrels',
    status: 'rejected',
    department: 'Wine making',
    type: 'Improvement',
    strategy: 'Employ best practice',
    workstation: 'Mentors',
    benefits: 'Improves barrel filling control through extended pump leads',
    resourcesRequired: 'high',
    submitter: 'Izele van Blerk',
    evaluator: 'Izele van Blerk',
    impactScore: 3,
    createdAt: '2025-07-08T00:00:00Z'
  },
  {
    id: 111,
    title: 'Filterability waste funnel for throwing out the wine',
    description: 'Filterability waste funnel for throwing out the wine to save time and streamline waste container emptying (print)',
    status: 'approved',
    department: 'Wine making',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: 'Mentors',
    benefits: 'Improves waste disposal efficiency through 3D printed funnel',
    resourcesRequired: 'low',
    submitter: 'Kyle Willard',
    evaluator: 'Kyle Willard',
    impactScore: 3,
    createdAt: '2025-07-09T00:00:00Z'
  },
  {
    id: 112,
    title: 'Acknowledgement of finding document include proposed root cause,actions,verification and status',
    description: 'Acknowledgement of finding document include proposed root cause,actions,verification and status of findings',
    status: 'approved',
    department: 'Quality',
    type: 'Improvement',
    strategy: 'Ensure continuous feedback and communication',
    workstation: 'Laboratory',
    benefits: 'Improves finding documentation through comprehensive tracking',
    resourcesRequired: 'low',
    submitter: 'Ilana Smit',
    evaluator: 'Ilana Smit',
    impactScore: 3,
    createdAt: '2025-07-09T00:00:00Z'
  },
  {
    id: 113,
    title: 'Create internal and external audit finding evidence email to whom QMM and QCA will have access to',
    description: 'Create internal and external audit finding evidence email to whom QMM and QCA will have access to.',
    status: 'approved',
    department: 'Quality',
    type: 'Improvement',
    strategy: 'Ensure responsiveness and urgency',
    workstation: 'Quality0compliance0auditing',
    benefits: 'Improves audit finding communication through dedicated email system',
    resourcesRequired: 'low',
    submitter: 'Ilana Smit',
    evaluator: 'Ilana Smit',
    impactScore: 3,
    createdAt: '2025-07-09T00:00:00Z'
  },
  {
    id: 114,
    title: 'Review Brittle glass breakage process',
    description: 'Review Brittle glass breakage process',
    status: 'approved',
    department: 'Quality',
    type: 'Improvement',
    strategy: 'Perform to world class standards',
    workstation: 'Quality0compliance0auditing',
    benefits: 'Optimizes glass breakage process through review',
    resourcesRequired: 'low',
    submitter: 'Ilana Smit',
    evaluator: 'Ilana Smit',
    impactScore: 3,
    createdAt: '2025-07-09T00:00:00Z'
  },
  {
    id: 115,
    title: 'Align different IPW inputs to one document',
    description: 'Align different IPW inputs to one document.',
    status: 'approved',
    department: 'Quality',
    type: 'Improvement',
    strategy: 'Employ best practice',
    workstation: 'Quality0compliance0auditing',
    benefits: 'Standardizes IPW inputs through document alignment',
    resourcesRequired: 'low',
    submitter: 'Carina Brand',
    evaluator: 'Carina Brand',
    impactScore: 3,
    createdAt: '2025-07-09T00:00:00Z'
  },
  {
    id: 116,
    title: 'Imported Products Procedure update to include new products',
    description: 'Imported Products Procedure update to include new products',
    status: 'approved',
    department: 'Quality',
    type: 'Improvement',
    strategy: 'Employ best practice',
    workstation: 'Quality0assurance',
    benefits: 'Keeps imported products procedure current with new additions',
    resourcesRequired: 'low',
    submitter: 'Nikki Baartzes',
    evaluator: 'Nikki Baartzes',
    impactScore: 3,
    createdAt: '2025-07-09T00:00:00Z'
  },
  {
    id: 117,
    title: 'Review internal pressure of corked products',
    description: 'Review internal pressure of corked products.',
    status: 'approved',
    department: 'Quality',
    type: 'Improvement',
    strategy: 'Employ best practice',
    workstation: 'Quality0control',
    benefits: 'Ensures corked product quality through pressure review',
    resourcesRequired: 'low',
    submitter: 'Nikki Baartzes',
    evaluator: 'Nikki Baartzes',
    impactScore: 3,
    createdAt: '2025-07-09T00:00:00Z'
  },
  {
    id: 118,
    title: 'Implement online survey for BSCI ethical questionnaire for business partners',
    description: 'Implement online survey for BSCI ethical questionnaire for business partners',
    status: 'approved',
    department: 'Quality',
    type: 'Improvement',
    strategy: 'Ensure continuous feedback and communication',
    workstation: 'Quality0control',
    benefits: 'Streamlines BSCI ethical questionnaire through online survey',
    resourcesRequired: 'low',
    submitter: 'Steveley August',
    evaluator: 'Steveley August',
    impactScore: 3,
    createdAt: '2025-07-09T00:00:00Z'
  },
  {
    id: 119,
    title: 'Compile 1-pagers for glass breakage procedures for departmental training purposes',
    description: 'Compile 1-pagers for glass breakage procedures for departmental training purposes',
    status: 'approved',
    department: 'Quality',
    type: 'Improvement',
    strategy: 'Employ best practice',
    workstation: 'Quality0assurance',
    benefits: 'Improves training efficiency through glass breakage 1-pagers',
    resourcesRequired: 'low',
    submitter: 'Nikki Baartzes',
    evaluator: 'Nikki Baartzes',
    impactScore: 3,
    createdAt: '2025-07-09T00:00:00Z'
  },
  {
    id: 120,
    title: 'Quarterly comparative analysis at the three laboratories',
    description: 'Quarterly comparative analysis at the three laboratories responsible for performing DALRRD testing',
    status: 'approved',
    department: 'Quality',
    type: 'Improvement',
    strategy: 'Continuously improve',
    workstation: 'Quality0control',
    benefits: 'Ensures testing consistency through quarterly laboratory analysis',
    resourcesRequired: 'low',
    submitter: 'Kyle Willard',
    evaluator: 'Kyle Willard',
    impactScore: 3,
    createdAt: '2025-07-09T00:00:00Z'
  },
  {
    id: 121,
    title: 'Create a PST2 whatsapp group for call or discussion',
    description: 'Create a PST2 whatsapp group for call or discussion',
    status: 'approved',
    department: 'Quality',
    type: 'Time saving',
    strategy: 'Ensure responsiveness and urgency',
    workstation: 'Laboratory',
    benefits: 'Improves communication efficiency through WhatsApp group',
    resourcesRequired: 'low',
    submitter: 'Nikki Baartzes',
    evaluator: 'Nikki Baartzes',
    impactScore: 3,
    createdAt: '2025-07-09T00:00:00Z'
  },
  {
    id: 122,
    title: 'Quick CIP chemical concentration verification in QC lab',
    description: 'Quick CIP chemical concentration verification in QC lab',
    status: 'approved',
    department: 'Quality',
    type: 'Time saving',
    strategy: 'Ensure accuracy',
    workstation: 'Quality0control',
    benefits: 'Improves CIP verification speed in QC lab',
    resourcesRequired: 'low',
    submitter: 'Nikki Baartzes',
    evaluator: 'Nikki Baartzes',
    impactScore: 3,
    createdAt: '2025-07-09T00:00:00Z'
  },
  {
    id: 123,
    title: 'A strainer to stop all the solid from being transferred from one tank to another',
    description: 'A strainer to stop all the solid from being transferred from one tank to another.It will be used to load product for export and can be used for offloading raw material.The strainers that was used for export was changed with a 100 microns sheet to stop hesian and pieces of the rubber balls in the piston pump to go through the strainer.',
    status: 'approved',
    department: 'Quality',
    type: 'Improvement',
    strategy: 'Deliver on customer expectation',
    workstation: 'Quality0control',
    benefits: 'Prevents solid transfer between tanks through strainer implementation',
    resourcesRequired: 'low',
    submitter: 'Dewald Louw',
    evaluator: 'Dewald Louw',
    impactScore: 3,
    createdAt: '2025-07-15T00:00:00Z'
  },
  {
    id: 124,
    title: 'If there is a fix stainless steel line from the loading area to the holding tank',
    description: 'If there is a fix stainless steel line from the loading area to the holding tank it will reduce the length of the 100mm flexi pipe. This will make it easier to store and handle the flexi pipe.The pipe is used daily during the months of February,March and April.',
    status: 'approved',
    department: 'Spirits',
    type: 'Time saving',
    strategy: 'Minimize waste',
    workstation: 'Worcester',
    benefits: 'Improves pipe handling efficiency through fixed stainless steel line',
    resourcesRequired: 'low',
    submitter: 'Dewald Louw',
    evaluator: 'Dewald Louw',
    impactScore: 3,
    createdAt: '2025-07-15T00:00:00Z'
  },
  {
    id: 125,
    title: 'The garden tools  in F10 is standing on the ground',
    description: 'The garden tools  in F10 is standing on the ground.The tools must be moved to G06 for better control over the garden tools and brackets must be made to hang the tools.',
    status: 'approved',
    department: 'Spirits',
    type: 'Improvement',
    strategy: 'Employ best practice',
    workstation: 'Worcester',
    benefits: 'Improves garden tool organization through proper storage',
    resourcesRequired: 'low',
    submitter: 'Dewald Louw',
    evaluator: 'Dewald Louw',
    impactScore: 3,
    createdAt: '2025-07-15T00:00:00Z'
  },
  {
    id: 126,
    title: 'There is no hose reels at G03, G04 and G07',
    description: 'There is no hose reels at G03, G04 and G07 . The hose pipe is laying on the ground because there is no hose reel.',
    status: 'approved',
    department: 'Spirits',
    type: 'Improvement',
    strategy: 'Employ best practice',
    workstation: 'Worcester',
    benefits: 'Improves hose organization through installation of hose reels',
    resourcesRequired: 'low',
    submitter: 'Dewald Louw',
    evaluator: 'Dewald Louw',
    impactScore: 3,
    createdAt: '2025-07-15T00:00:00Z'
  },
  {
    id: 127,
    title: 'Change the platform in the H camp and replace the ladder',
    description: 'Change the platform in the H camp and replace the ladder. The ladder is unsafe. You can slip and fall. If a truck is loaded there is no entry for the pipe except for the gate. This make it difficult to attach the pipe to the tank pipe line.',
    status: 'approved',
    department: 'Spirits',
    type: 'Safety',
    strategy: 'Employ best practice',
    workstation: 'Worcester',
    benefits: 'Enhances H camp safety through platform and ladder replacement',
    resourcesRequired: 'low',
    submitter: 'Dewald Louw',
    evaluator: 'Dewald Louw',
    impactScore: 3,
    createdAt: '2025-07-15T00:00:00Z'
  },
  {
    id: 128,
    title: 'Use a sticker seal on the containers',
    description: 'Use a sticker seal on the containers.When loading product the client want the safety valve to be seal.There is sometimes no fitting to put the seal through and the valve can not be sealed.Using sticker seals from SGS will resolve the problem',
    status: 'approved',
    department: 'Spirits',
    type: 'Product',
    strategy: 'Deliver on customer expectation',
    workstation: 'Worcester',
    benefits: 'Improves container sealing through sticker seal implementation',
    resourcesRequired: 'low',
    submitter: 'Dewald Louw',
    evaluator: 'Dewald Louw',
    impactScore: 3,
    createdAt: '2025-07-15T00:00:00Z'
  },
  {
    id: 129,
    title: 'make brackets for fittings at G03,G04 and F10',
    description: 'make brackets for fittings at G03,G04 and F10.Equipment is store neatly.If equipment is not on brackets end off day report it at MDTW.If employee is sick the next employee know were the equipment is to do transfers,load trucks or offload trucks',
    status: 'approved',
    department: 'Spirits',
    type: 'Improvement',
    strategy: 'Employ best practice',
    workstation: 'Worcester',
    benefits: 'Improves equipment organization through bracket installation',
    resourcesRequired: 'low',
    submitter: 'Dewald Louw',
    evaluator: 'Dewald Louw',
    impactScore: 3,
    createdAt: '2025-07-15T00:00:00Z'
  },
  {
    id: 130,
    title: 'move cabinet at wine offloading to F10 store for sample bottles during harvest time',
    description: 'move cabinet at wine offloading to F10 store for sample bottles during harvest time',
    status: 'approved',
    department: 'Spirits',
    type: 'Improvement',
    strategy: 'Employ best practice',
    workstation: 'Worcester',
    benefits: 'Improves sample bottle storage during harvest through cabinet relocation',
    resourcesRequired: 'low',
    submitter: 'Dewald Louw',
    evaluator: 'Dewald Louw',
    impactScore: 3,
    createdAt: '2025-07-15T00:00:00Z'
  },
  {
    id: 131,
    title: 'Make a drive through between G06 and G06A',
    description: 'Make a drive through between G06 and G06A. One between G05 and G04. It will reduce time and save gas. Forklift have to drive  around G06 stores to get to maturation stores',
    status: 'under_review',
    department: 'Spirits',
    type: 'Time saving',
    strategy: 'Minimize cost',
    workstation: 'Worcester',
    benefits: 'Reduces forklift travel time through drive-through creation',
    resourcesRequired: 'medium',
    submitter: 'Olwethu Mzamo',
    evaluator: 'Dewald Louw',
    impactScore: 3,
    createdAt: '2025-07-15T00:00:00Z'
  },
  {
    id: 132,
    title: 'A program written on excel for the weighbridge operator',
    description: 'A program written on excel for the weighbridge operator.He only type in the net weight that he gets from the weighbridge and alcohol that he gets from the lab in the program and it will give you the liters,Laa and density',
    status: 'approved',
    department: 'Spirits',
    type: 'Time saving',
    strategy: 'Ensure accuracy',
    workstation: 'Worcester',
    benefits: 'Improves weighbridge efficiency through Excel program',
    resourcesRequired: 'low',
    submitter: 'Dewald Louw',
    evaluator: 'Dewald Louw',
    impactScore: 3,
    createdAt: '2025-07-15T00:00:00Z'
  }
]

export default eventHandler(async () => {
  return ideas
})
